packetdrill-ext-libs := -lpcap
CFLAGS = -D__APPLE_USE_RFC_3542 -Wall -Werror -Wno-unknown-warning-option
LDFLAGS =
ifneq ("$(wildcard /usr/lib/libsctp.dylib)","")
    packetdrill-ext-libs += -lsctp
    CFLAGS += -DHAVE_SCTP
endif
include Makefile.common
