packetdrill-ext-libs := -pthread -lpcap
CFLAGS = -D__APPLE_USE_RFC_3542
LDFLAGS =
ifeq ("$(wildcard $(/usr/lib/libsctp.dylib))","")
    packetdrill-ext-libs += -lsctp
    CFLAGS += -DHAVE_SCTP
endif
include Makefile.common
